env:
    CONFIG: config.sh
    CIRRUS_SHELL: bash
    TG_TOKEN: ENCRYPTED[fa1223b89c143815f186694852c9a5829a6477d80ef6d82e0540a7f4fc345cd97f22867b47d5db6225cdbe79f65d0ae2]

task:
  name: "CirrusCI-Recovery-Builder"
  timeout_in: 120m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 20G

  Sync_script:
      - curl -sL https://github.com/ShazuxD/CirrusCI-Recovery-Builder/raw/main/scripts/sync.sh | bash
  Build_script:
      - curl -sL https://github.com/ShazuxD/CirrusCI-Recovery-Builder/raw/main/scripts/build.sh | bash
  Upload_script:
      - curl -sL https://github.com/ShazuxD/CirrusCI-Recovery-Builder/raw/main/scripts/upload.sh | bash
